version: '3.8'
services:
  app:
    image: breast-milk-tracker:latest
    build: .
    container_name: bmt
    env_file:
      - ./.env
    environment:
      # Optional: override via .env
      NODE_ENV: ${NODE_ENV}
      PRINTER: ${PRINTER}
      LABEL_MEDIA: ${LABEL_MEDIA}
      ORIENTATION: ${ORIENTATION}
      PRINT_FIT: ${PRINT_FIT}
      # Set timezone to match the Pi host
      TZ: America/New_York
    volumes:
      - ./backend/data.json:/app/data.json
      # Mount CUPS config so container can access host CUPS daemon
      - /etc/cups/client.conf:/etc/cups/client.conf:ro
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
    # Enable access to USB devices for direct printer access
    devices:
      - /dev/usb:/dev/usb
    # Use host network to access CUPS daemon
    network_mode: host
